### ISSUE TITLE
Install Nebulosa on R 3.6.3

### ISSUE THREAD

**Issue by MelissaSaichi** [powellgenomicslab/Nebulosa#2]
Hello,
I was wondering whether it is possible to get "Nebulosa" installed in R version 3.6.3. thanks

**Comment by joseah** [comment]
Hi Melissa, 

I've set the restriction for `R >= 4.0.0` to comply with the Bioconductor requirements. However, I created a version without that restriction that you can install from this repo for older versions of R: https://github.com/powellgenomicslab/Nebulosa_Rv3

Feel free to open an issue in that repo if you have any issues with the installation.
