### ISSUE TITLE
Does Nebulosa support the visualization of CITE-seq data?

### ISSUE THREAD

**Issue by lxhuang7** [powellgenomicslab/Nebulosa#3]
Hi Jose,

Thank you for creating this wonderful new package! I was wondering if it could be used to visualize the marker gene and antibody expression data from CITE-seq simultaneously, just like the FeaturePlot function in Seurat? I tried to read the source code but was not sure how plot_density() can search both RNA and ADT assay for expression data at the same time. 

Thanks,
Lei

**Comment by joseah** [comment]
Hi Lei,

yes, I'm currently working on a vignette. You can use the same syntax as in Seurat to plot features from multiple modalities. 
For example:

```r
plot_density(object, c("CD14", "adt_CD14"))
```

The data to be plotted is recovered via `FetchData()` so you can add the prefix "adt_" to the CITE-seq markers.
The previous will work if your default assay is `RNA` or `SCT`. 

If your default assay is `ADT` then you would need to do the following:

```r
plot_density(object, c("rna_CD14",  "CD14"))
```

Let me know if this works for you. 
Cheers.

**Comment by lxhuang7** [comment]
Thanks for the detailed explanation, Jose! This is very helpful.
